### ISSUE TITLE
On npmjs.com, package short description in list display and search results shows markup

### ISSUE THREAD

**Issue by dthyresson** [redwoodjs/create-redwood-app#103]
When searching for `create-redwood-app` on npmjs.com, the serch results and short display renders markdown instyead of more human friendly text:

![image](https://user-images.githubusercontent.com/1051633/93077913-8d36fc00-f657-11ea-80c3-9e348974c6cf.png)

![image](https://user-images.githubusercontent.com/1051633/93077948-9b851800-f657-11ea-9f14-9fffe6e9f80e.png)

Note: I searched the repo for "purpose" and could not find where this markdown comes from.

**Comment by thedavidprice** [comment]
@jtoar I added this to our Documentation project. Decent low-hanging fruit that would tidy things up.

**Comment by jacebenson** [comment]
I think this somehow is reading the readme from here: https://github.com/redwoodjs/redwood/blob/master/packages/create-redwood-app/README.md

**Comment by dthyresson** [comment]
See: https://docs.npmjs.com/creating-a-package-json-file

```
You can add a package.json file to your package to make it easy for others to manage and install. Packages published to the registry must contain a package.json file.

A package.json file:

lists the packages your project depends on
specifies versions of a package that your project can use using semantic versioning rules
makes your build reproducible, and therefore easier to share with other developers
```

>Note: To make your package easier to find on the npm website, we recommend including a custom description in your package.json file.


Perhaps then the solution is to add a "description" to 

https://github.com/redwoodjs/redwood/blob/main/packages/create-redwood-app/package.json

?

**Comment by jacebenson** [comment]
That wouldbe the right approach.  Thanks @dthyresson

**Comment by thedavidprice** [comment]
Did it!
https://www.npmjs.com/package/create-redwood-app
