### ISSUE TITLE
The system cannot find the path specified. yarn create redwood-app not working but create-redwood-app working.

### ISSUE THREAD

**Issue by oguzhnatly** [redwoodjs/create-redwood-app#121]
Just look at the code below. create-redwood-app is working but yarn create redwood-app is not working.
```bash
D:\redwoodjs>create-redwood-app
Please specify the project directory
  yarn create redwood-app <project-directory>

For example:
  yarn create redwood-app my-redwood-app

D:\redwoodjs>yarn create redwood-app redwood-blog
yarn create v1.22.5
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.13: The platform "win32" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "create-redwood-app@0.21.0" with binaries:
      - create-redwood-app
The system cannot find the path specified.
error Command failed.
Exit code: 1
Command: C:\Users\MSİ\AppData\Local\Yarn\Data\global\node_modules\bin\create-redwood-app
Arguments: redwood-blog
Directory: D:\redwoodjs
Output:

info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.
```
```
yarn -v
1.22.5

node -v
v12.12.0

npm -v
6.11.3
```
It causes totally the same error with windows command console and Powershell. My system has Windows 10x64. I also use nvm. I've tried this with two node version: v12.11.1 and v12.12.0. I checked https://github.com/redwoodjs/create-redwood-app/issues/54#issuecomment-619629699 out and it didn't work.

**Comment by thedavidprice** [comment]
Hi @oguzhnatly! Thanks for checking in about this.

Just to confirm, _are_ you adding a directory option to the command when it's run? E.g:
```
yarn create redwood-app directory/of/my-app
```

The command needs to know where to install and will fail otherwise. (That's what the error above is, poorly, identifying.)

- if you are providing a directory to the command, there's definitely something more going on. Please do provide more info
- otherwise, I agree we could improve the error handling and output in this case... perhaps even provide a default with user input confirmation to proceed --> or better yet prompt the user for the directory! Could you create a new Issue in the main repo if this makes sense? https://github.com/redwoodjs/redwood/issues

---

Keep me posted!

**Comment by oguzhnatly** [comment]
Thanks for the answer @thedavidprice! 
Actually, I solve this issue in an alternative way with this:
```
create-redwood-app redwood-blog
```
instead of this:
```
yarn create redwood-app redwood-blog
```
I still don't know why the second one is not working. I don't believe that the windows10 environment path causes this problem because react and vue scripts were working with this env. configurations.
By the way, I was not adding a directory option with that command when it's run. I was just creating a new redwood app.

As I said, I solve it by typing `create redwood-app redwood-blog`. However, I wonder if any other error causes this problem in yarn create or any windows10 environment path causes it. Therefore I want to create a new issue in the main repo, should I still create new issue for that reason?

**Comment by thedavidprice** [comment]
>So I want to create a new issue in the main repo, and also I was not providing a directory. Therefore, should I still create a new issue for that reason?

Yes, please! That would be very helpful. Please include:
- your system info and windows terminal you're using
- versions of yarn and node you have installed
- command you ran and the error output

Thanks again for the help. And, most importantly, glad you got it working!
