### ISSUE TITLE
fineOne -> findUnique

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/create-redwood-app#122]
Prisma is deprecating `findOne()` as of 2.12.0 We have several comments in generated code that mention using `findOne()`. We gotta update those!

**Comment by robobunny** [comment]
It's not clear to me how exactly to fix this, since I'm not finding any instances of `findOne` in this repo. 

Is this a fix that needs to happen in the /redwood repo? if so, I think I have a PR ready to go. Otherwise, can you suggest a course of action?

Thanks!

**Comment by cannikin** [comment]
Ahhh you're right, I forgot this repo doesn't come with `api/src/lib/auth.js` — it's generated by the main redwood repo once you introduce authorization. Closing!
