### ISSUE TITLE
Closing this Repo after v0.24.0 release

### ISSUE THREAD

**Issue by jvanbaarsen** [redwoodjs/create-redwood-app#126]
@thedavidprice Should we close down this repo now that we pulled this into the main RW repo? Otherwise we could create some confusion. We have 3 open PRs for which we need to decide what to do with them.

**Comment by thedavidprice** [comment]
Once v0.24.0 is released (should be this week), it will be time to archive this Repo. 2 of the 3 open PRs are stale and from Peter and me. I have already informed Danny that he needs to move his PR to the main repo.

I did change this Issue title and will pin it to the top of the Issues page. Also, I am watching for incoming.

Any other suggestions for quick/easy messaging this week? Thanks!

**Comment by thedavidprice** [comment]
archiving now

😢
