### ISSUE TITLE
Update README with new Prisma package names

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/create-redwood-app#14]
Currently says:

We're using Prisma's [Photon ORM](https://github.com/prisma/prisma2/blob/master/docs/photon/api.md) and [Lift Migration Engine](https://github.com/prisma/prisma2/blob/master/docs/data-modeling.md).

**Comment by peterp** [comment]
Closed in a1884daf17c2b027ea9171e591fd9a31124dea53
