### ISSUE TITLE
Add redirects so all URLs map to index.html

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/create-redwood-app#22]
Once copy-webpack-plugin from @thedavidprice is merged, put `_redirects` in `web/public`

**Comment by peterp** [comment]
It looks like we can also do this via `netlify.toml`:
https://docs.netlify.com/configure-builds/file-based-configuration/#redirects

**Comment by cannikin** [comment]
Ahhh yeah that's cleaner than adding a separate file. I'll do that!
