### ISSUE TITLE
Add /lib directory to /api and /web

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/create-redwood-app#45]
After our weekly meeting we decided on doing this in lieu of: https://github.com/redwoodjs/redwood/issues/299

**Comment by thedavidprice** [comment]
@cannikin Question: should we support this with README in the folder and/or info via a Doc or Tutorial? Overall I think this will be intuitive to those who want to use it, but specificity might be helpful. (Thinking out loud...)

**Comment by peterp** [comment]
Closed by #47
