### ISSUE TITLE
Add prisma.prisma to VS Code extension recommendations? 

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/create-redwood-app#46]
I think we are all using `prisma.prisma` ourselves. Does it make sense to add here:

`.vscode/extensions.json`

?

**Comment by peterp** [comment]
I added it https://github.com/redwoodjs/create-redwood-app/blob/7e9f29e6581a4f016c4cfd27fe38d9565e35dcc8/.vscode/extensions.json#L10

**Comment by satyarohith** [comment]
Cool. I suppose we can close this. :)

**Comment by thedavidprice** [comment]
Yes indeed.
