### ISSUE TITLE
Create Netlify build plugin for replacing Prisma provider

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/create-redwood-app#49]
After discussions with Netlify it looks like we can create a build plugin to replace the provider at build time! https://github.com/netlify/build This will be our workaround until https://github.com/prisma/prisma/issues/1487 is resolved.

* If it's a local plugin then we'll need to create `./plugins/netlify-plugin-prisma-provider.js`. 
* If we make it a community plugin then we'll just need an update to `netlify.toml`

**Comment by peterp** [comment]
@cannikin This is done, right?

**Comment by cannikin** [comment]
YES! Closing
