### ISSUE TITLE
`yarn create redwood-app ./redwoodblog` fails on every OS

### ISSUE THREAD

**Issue by ryancwalsh** [redwoodjs/create-redwood-app#54]
I just found Redwood today and was excited to start the tutorial at https://redwoodjs.com/tutorial/installation-starting-development

Unfortunately `yarn create redwood-app ./redwoodblog` does not work for me:

```
success Installed "create-redwood-app@0.6.0" with binaries:
      - create-redwood-app
internal/modules/cjs/loader.js:1174
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/vagrant/.config/yarn/global/node_modules/is-promise/index.js
require() of ES modules is not supported.
require() of /home/vagrant/.config/yarn/global/node_modules/is-promise/index.js from /home/vagrant/.config/yarn/global/node_modules/listr/lib/task.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/vagrant/.config/yarn/global/node_modules/is-promise/package.json.
```

I have tried on Mac, Windows 10 in PowerShell as Admin, and Homestead Vagrant Ubuntu VM on Win 10 host. They all fail at this very first step.

**Comment by thedavidprice** [comment]
Hi @ryancwalsh Sorry you hit a roadblock right out of the gate! We'll try to get you going as fast as we can. 🚀

## Manual Installation Process
It's not ideal, but you _can_ manually bootstrap Redwood with relative ease. [Here are the instructions on our community forums](https://community.redwoodjs.com/t/how-to-manually-bootstrap-install-create-redwood-app/115).

However, if you do have issues related to your Node and Yarn versions (see below), you'll again run into errors with "Engines node supported" when you try to `yarn install`.

## Debugging
Unfortunately, I can't reproduce this error on my Mac. Here's my system info:
```shell
    OS: macOS 10.15.4
    Node: 12.16.0
    Yarn: 1.22.4
```
Based on this line in your error output above, `Error [ERR_REQUIRE_ESM]: Must use import to load ES Module:` I suspect there's something not working related to your version(s) of Node and Yarn. Or, perhaps, your possible use of a version manager for Node. (Here's another thread on our forums related to[ running multiple versions](https://community.redwoodjs.com/t/installation-error-multiple-versions-of-yarn-or-using-version-manager-other-than-nvm/102).)

Questions:
- what [versions of Yarn and Node do you have installed](https://redwoodjs.com/tutorial/prerequisites)?
- are you using something like NVM to manage Node versions? And/or how did you install Node and Yarn?

**Comment by ryancwalsh** [comment]
Wow! Thanks for the fast response. I happened to figure out right before seeing your answer that **downgrading node from v12.16.1 to 12.11 fixes it:**

https://github.com/facebook/create-react-app/issues/8900#issuecomment-619413214

Given what you saw, maybe I could have downgraded to 12.16.0.

Thanks!

**Comment by ryancwalsh** [comment]
In case it helps anyone else, what I did yesterday (if I remember correctly) was in my virtual machine:

```
node -v
sudo mkdir -p /usr/local/n
sudo chown -R $(whoami) /usr/local/n
sudo chown -R $(whoami) /usr/local/bin /usr/local/lib /usr/local/include /usr/local/share
npm install -g n
n 12.12
node -v
yarn create redwood-app ./redwoodblog
```

See:

https://github.com/tj/n/issues/416#issuecomment-417808320

https://stackoverflow.com/questions/47008159/how-to-downgrade-node-version#comment108669144_50287454

Today, I'm creating a new app (not the tutorial) and am on Windows 10 [using straight Git Bash](https://github.com/redwoodjs/redwood/issues/475#issuecomment-619558971) without using SSH to go into a VM.

My NodeJs was 12.16, which causes errors, so I needed to uninstall Node completely from Windows and then install https://github.com/coreybutler/nvm-windows and then:

```
nvm install 12.12
nvm use 12.12.0
node -v
```

Now `yarn create redwood-app` works.
