### ISSUE TITLE
internal/modules/cjs/loader.js:1172       throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);

### ISSUE THREAD

**Issue by MarwenHanzouli** [redwoodjs/create-redwood-app#55]
![image](https://user-images.githubusercontent.com/44104230/80289520-c5847f00-8736-11ea-90ff-ccdd755451f8.png)

![image](https://user-images.githubusercontent.com/44104230/80289461-72aac780-8736-11ea-8e05-90d1d30fc45e.png)

i have this error when i tried to generate a new page in ionic 4 with angular type

**Comment by thedavidprice** [comment]
Hi @MarwenHanzouli I believe you have the incorrect project. This is for RedwoodJS. See https://redwoodjs.com

However, that error is familiar as Node 12.16.1 has been causing issues for people and throwing a `Require ESM` error. See this Issue in Create React App for details:
https://github.com/facebook/create-react-app/issues/8900#issuecomment-619413214

Hope that helps. Closing this out.
