### ISSUE TITLE
Update location of schema.prisma in netlify.toml

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/create-redwood-app#59]
Assuming this works https://github.com/redwoodjs/redwood/issues/620 we need to tell the provider plugin where to go to find schema.prisma.

**Comment by dhausser** [comment]
Is this issue still valid? If so, can I would like to fix it.

**Comment by peterp** [comment]
I don't think we use the provider plugin anymore, but I do think that we want to move the directory from `./api/prisma` to `./api/db` in #620

It would be amazing if you could do that!

**Comment by dhausser** [comment]
Sure thing! Should be done with https://github.com/redwoodjs/create-redwood-app/pull/112.

**Comment by thedavidprice** [comment]
@cannikin Thoughts about just closing this one out 'cause no more focus on Netlify Provider Plugin?
