### ISSUE TITLE
Ship with launch.json file for debugging and setting breakpoints.

### ISSUE THREAD

**Issue by guledali** [redwoodjs/create-redwood-app#64]
We should add a `launch.json` for debugging server related code

https://m.youtube.com/watch?v=JdvkaW2xeiI

**Comment by peterp** [comment]
Oooh, yes please, I would love to understand how that works!

**Comment by guledali** [comment]
No need to mess up with .vscode/launch.json, just follow the official Auto Attach intro and ... Just Works!

https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_auto-attach-feature
