### ISSUE TITLE
yarn create redwood-app fails with node incompatibility

### ISSUE THREAD

**Issue by divyenduz** [redwoodjs/create-redwood-app#72]
```
divyendusingh [playground]$ yarn create redwood-app ./w3z                                                                                                        130 ↵
yarn create v1.22.4
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error ghost-cli@1.11.0: The engine "node" is incompatible with this module. Expected version "^8.9.0 || ^10.13.0". Got "12.18.2"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.
```

Environment

```
OS: macOS 10.15.5
Node: 12.18.2
Yarn: 1.22.4
```

Using node `v10.16.3` works past this issue but fails at a later validation

```
divyendusingh [playground]$ yarn create redwood-app ./w3z
yarn create v1.17.3
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Installed "create-redwood-app@0.12.0" with binaries:
      - create-redwood-app
  ✔ Creating Redwood app
    ✔ Creating directory '/Users/divyendusingh/Documents/zoid/playground/w3z'
    ✔ Downloading latest release
    ✔ Extracting latest release
    ✔ Clean up
  ❯ Installing packages
    ✖ Checking node and yarn compatibility
      → yarn >=1.15.0 required, but you have 1.17.3.
      Running `yarn install`... (This could take a while)

{ Error: node >=12.0.0 required, but you have 10.16.3.
yarn >=1.15.0 required, but you have 1.17.3.
    at /Users/divyendusingh/.config/yarn/global/node_modules/create-redwood-app/dist/create-redwood-app.js:152:25
    at parallel (/Users/divyendusingh/.config/yarn/global/node_modules/check-node-version/index.js:163:5)
    at end (/Users/divyendusingh/.config/yarn/global/node_modules/run-parallel/index.js:18:15)
    at done (/Users/divyendusingh/.config/yarn/global/node_modules/run-parallel/index.js:22:10)
    at each (/Users/divyendusingh/.config/yarn/global/node_modules/run-parallel/index.js:28:7)
    at /Users/divyendusingh/.config/yarn/global/node_modules/run-parallel/index.js:38:43
    at exec (/Users/divyendusingh/.config/yarn/global/node_modules/check-node-version/index.js:201:16)
    at ChildProcess.exithandler (child_process.js:285:7)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16) context: [Object: null prototype] {} }
error Command failed.
Exit code: 1
Command: /usr/local/bin/create-redwood-app
Arguments: ./w3z
Directory: /Users/divyendusingh/Documents/zoid/playground
Output:

info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.
```

I was able to unblock myself by following the manual bootstrap process though https://community.redwoodjs.com/t/how-to-manually-bootstrap-install-create-redwood-app/115 🙌

**Comment by thedavidprice** [comment]
Hi @divyenduz apologies for the silence on this end. We're mostly watching the `redwoodjs/redwood` repo for issues, which we could probably make more clear.

Glad you were able to find the workaround in the Forum. But bummer you ran into the false "version requirement not met". Any chance you're using a Node version manager like [NVM](https://github.com/nvm-sh/nvm/blob/master/README.md)? We've seen this problem before but it's been related to having multiple versions installed and a system default that doesn't meet the engine requirements — curious if that might apply to this case.

Lastly, I've long has the outstanding task to add a Preflight Check to the installation script so this happens _before_ anything begins. This is a good prompt to get back focused on that one. 😬

Hope Redwood has been treating you overall!

**Comment by divyenduz** [comment]
> Any chance you're using a Node version manager like NVM?

That is true

> Preflight Check to the installation script

That would be good but it working with nvm will be even more awesome :)

**Comment by thedavidprice** [comment]
100% understood. And the installation does work with NVM (I use NVM). It's how NVM is setup locally that we can't control but could probably find ways to work around over time. 

Here's a forum topic with background and links with the relevant discussion if interested/helpful:
https://community.redwoodjs.com/t/installation-error-multiple-versions-of-yarn-or-using-version-manager-other-than-nvm/102

Thanks again.
